# https://thuanbui.me/tao-object-storage-server-voi-minio-docker/#ii-cai-dat-minio-bang-docker

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: huynhdn
      MINIO_ROOT_PASSWORD: abcd1234
    command: server --console-address ":9001" /data